name: prod

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.UKRAINE_HOSTING_SSH_HOST }}
          username: ${{ secrets.UKRAINE_HOSTING_SSH_USERNAME }}
          key: ${{ secrets.UKRAINE_HOSTING_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ secrets.UKRAINE_HOSTING_SITE_PATH }}
            rm -rf .next/static
            rm -rf .next/standalone/public
            rm -rf .next/standalone/.next/static
            git pull
            npm install
            npm run build
    
      - name: Reload Node.js Application
        run: |
          curl -X POST "https://adm.tools/action/hosting/account/nodejs/reload/" \
            -H "Authorization: Bearer ${{ secrets.UKRAINE_HOSTING_API_TOKEN }}" \
            -d "host_id=${{ secrets.UKRAINE_HOSTING_SITE_HOST_ID }}"

      - name: Notify Telegram
        if: always()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TG_NOTIFY_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TG_NOTIFY_CHAT_ID }}
          MESSAGE_THREAD_ID: ${{ secrets.TG_NOTIFY_CHAT_THREAD_ID }}
          PROJECT_NAME: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_TIMESTAMP: ${{ github.event.head_commit.timestamp }}
          JOB_STATUS: ${{ job.status }}
          WEBSITE_URL: ${{ secrets.PRODUCTION_SITE_URL }}
        run: |
          if [[ "${JOB_STATUS}" == "success" ]]; then
            TITLE="🚀 Деплой успішно завершено!"
          elif [[ "${JOB_STATUS}" == "failure" ]]; then
            TITLE="❌ Деплой завершився з помилкою!"
          elif [[ "${JOB_STATUS}" == "cancelled" ]]; then
            TITLE="⚠️ Деплой скасовано!"
          fi

          RAW_TIMESTAMP=${COMMIT_TIMESTAMP}
          export TZ="Europe/Kyiv"
          STYLED_TIMESTAMP=$(date -d "${RAW_TIMESTAMP}" "+%d.%m.%Y о %H:%M")
          PROJECT_SHORT_NAME=$(basename "${PROJECT_NAME}")
          TEXT="<blockquote>${TITLE}</blockquote>%0A🛠️ <b>Репо:</b> ${PROJECT_SHORT_NAME} (🌿 ${BRANCH_NAME})%0A✏️ <b>Коміт:</b> ${COMMIT_MESSAGE} (від ${STYLED_TIMESTAMP})%0A🌐 <b>Сайт:</b> <a href='https://${WEBSITE_URL}'>${WEBSITE_URL}</a>"
          
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
          -d chat_id=${CHAT_ID} \
          -d message_thread_id=${MESSAGE_THREAD_ID} \
          -d parse_mode="HTML" \
          -d disable_web_page_preview=true \
          -d text="${TEXT}"
